const data = {
  data: [
    {
      firstName: "Kate",
      lastName: "Boisson",
      email: "KateBoisson@gmail.com",
      contact: "(907)694-7675",
      address: "23475 Glacier View Dr, Eagle River, Alaska 99577, USA",
      dept: "",
      role: "Partner",
      city: "Eagle River",
      state: "Alaska",
      zip: "99577",
      country: "USA",
      pass: "1234",
      id: 1,
      src: "https://i.postimg.cc/90mcVfBq/unsplash-m-EZ3-Po-FGs-k.jpg",
    },
    {
      firstName: "Sarthak",
      lastName: "Sachdeva",
      email: "KateBoisson@gmail.com",
      contact: "(907)694-7675",
      address: "23475 Glacier View Dr, Eagle River, Alaska 99577, USA",
      dept: "",
      role: "Partner",
      city: "Eagle River",
      state: "Alaska",
      zip: "99577",
      country: "USA",
      pass: "1234",
      id: 2,
      src: "https://i.postimg.cc/90mcVfBq/unsplash-m-EZ3-Po-FGs-k.jpg",
    },
    {
      firstName: "Kate",
      lastName: "Boisson 3",
      email: "KateBoisson@gmail.com",
      contact: "(907)694-7675",
      address: "23475 Glacier View Dr, Eagle River, Alaska 99577, USA",
      dept: "",
      role: "Partner",
      city: "Eagle River",
      state: "Alaska",
      zip: "99577",
      country: "USA",
      pass: "1234",
      id: 3,
      src: "https://i.postimg.cc/90mcVfBq/unsplash-m-EZ3-Po-FGs-k.jpg",
    },
    {
      firstName: "Kate",
      lastName: "Boisson 4",
      email: "KateBoisson@gmail.com",
      contact: "(907)694-7675",
      address: "23475 Glacier View Dr, Eagle River, Alaska 99577, USA",
      dept: "",
      role: "Partner",
      city: "Eagle River",
      state: "Alaska",
      zip: "99577",
      country: "USA",
      pass: "1234",
      id: 4,
      src: "https://i.postimg.cc/90mcVfBq/unsplash-m-EZ3-Po-FGs-k.jpg",
    },
    {
      firstName: "Kate",
      lastName: "Boisson 5",
      email: "KateBoisson@gmail.com",
      contact: "(907)694-7675",
      address: "23475 Glacier View Dr, Eagle River, Alaska 99577, USA",
      dept: "",
      role: "Partner",
      city: "Eagle River",
      state: "Alaska",
      zip: "99577",
      country: "USA",
      pass: "1234",
      id: 5,
      src: "https://i.postimg.cc/90mcVfBq/unsplash-m-EZ3-Po-FGs-k.jpg",
    },
    {
      firstName: "Kate",
      lastName: "Boisson 6",
      email: "KateBoisson@gmail.com",
      contact: "(907)694-7675",
      address: "23475 Glacier View Dr, Eagle River, Alaska 99577, USA",
      dept: "",
      role: "Partner",
      city: "Eagle River",
      state: "Alaska",
      zip: "99577",
      country: "USA",
      pass: "1234",
      id: 6,
      src: "https://i.postimg.cc/90mcVfBq/unsplash-m-EZ3-Po-FGs-k.jpg",
    },
  ],
};

export default data;
