const data = {
  data: [
    {
      firstName: "Kate",
      lastName: "Boisson 1",
      src: "https://i.postimg.cc/90mcVfBq/unsplash-m-EZ3-Po-FGs-k.jpg",
      email: "KateBoisson@gmail.com",
      role: "Partner",
      contactNumber: "(907)694-7675",
      address: "23475 Glacier View Dr, Eagle River, Alaska 99577, USA",
      id: 1,
    },
    {
      firstName: "Kate",
      lastName: "Boisson 2",
      src: "https://i.postimg.cc/90mcVfBq/unsplash-m-EZ3-Po-FGs-k.jpg",
      email: "KateBoisson@gmail.com",
      role: "Manager",
      contactNumber: "(907)694-7675",
      address: "23475 Glacier View Dr, Eagle River, Alaska 99577, USA",
      id: 2,
    },
    {
      firstName: "Kate",
      lastName: "Boisson 3",
      src: "https://i.postimg.cc/90mcVfBq/unsplash-m-EZ3-Po-FGs-k.jpg",
      email: "KateBoisson@gmail.com",
      role: "Team",
      contactNumber: "(907)694-7675",
      address: "23475 Glacier View Dr, Eagle River, Alaska 99577, USA",
      id: 3,
    },
    {
      firstName: "Kate",
      lastName: "Boisson 4",
      src: "https://i.postimg.cc/90mcVfBq/unsplash-m-EZ3-Po-FGs-k.jpg",
      email: "KateBoisson@gmail.com",
      role: "Partner",
      contactNumber: "(907)694-7675",
      address: "23475 Glacier View Dr, Eagle River, Alaska 99577, USA",
      id: 4,
    },
    {
      firstName: "Kate",
      lastName: "Boisson 5",
      src: "https://i.postimg.cc/90mcVfBq/unsplash-m-EZ3-Po-FGs-k.jpg",
      email: "KateBoisson@gmail.com",
      role: "Manager",
      contactNumber: "(907)694-7675",
      address: "23475 Glacier View Dr, Eagle River, Alaska 99577, USA",
      id: 5,
    },
    {
      firstName: "Kate",
      lastName: "Boisson 6",
      src: "https://i.postimg.cc/90mcVfBq/unsplash-m-EZ3-Po-FGs-k.jpg",
      email: "KateBoisson@gmail.com",
      role: "Partner",
      contactNumber: "(907)694-7675",
      address: "23475 Glacier View Dr, Eagle River, Alaska 99577, USA",
      id: 6,
    },
    {
      firstName: "Kate",
      lastName: "Boisson 7",
      src: "https://i.postimg.cc/90mcVfBq/unsplash-m-EZ3-Po-FGs-k.jpg",
      email: "KateBoisson@gmail.com",
      role: "Partner",
      contactNumber: "(907)694-7675",
      address: "23475 Glacier View Dr, Eagle River, Alaska 99577, USA",
      id: 7,
    },
    {
      firstName: "Kate",
      lastName: "Boisson 8",
      src: "https://i.postimg.cc/90mcVfBq/unsplash-m-EZ3-Po-FGs-k.jpg",
      email: "KateBoisson@gmail.com",
      role: "Partner",
      contactNumber: "(907)694-7675",
      address: "23475 Glacier View Dr, Eagle River, Alaska 99577, USA",
      id: 8,
    },
    {
      firstName: "Kate",
      lastName: "Boisson 9",
      src: "https://i.postimg.cc/90mcVfBq/unsplash-m-EZ3-Po-FGs-k.jpg",
      email: "KateBoisson@gmail.com",
      role: "Manager",
      contactNumber: "(907)694-7675",
      address: "23475 Glacier View Dr, Eagle River, Alaska 99577, USA",
      id: 9,
    },
    {
      firstName: "Kate",
      lastName: "Boisson 10",
      src: "https://i.postimg.cc/90mcVfBq/unsplash-m-EZ3-Po-FGs-k.jpg",
      email: "KateBoisson@gmail.com",
      role: "Team",
      contactNumber: "(907)694-7675",
      address: "23475 Glacier View Dr, Eagle River, Alaska 99577, USA",
      id: 10,
    },
    {
      firstName: "Kate",
      lastName: "Boisson 11",
      src: "https://i.postimg.cc/90mcVfBq/unsplash-m-EZ3-Po-FGs-k.jpg",
      email: "KateBoisson@gmail.com",
      role: "Partner",
      contactNumber: "(907)694-7675",
      address: "23475 Glacier View Dr, Eagle River, Alaska 99577, USA",
      id: 11,
    },
    {
      firstName: "Kate",
      lastName: "Boisson 12",
      src: "https://i.postimg.cc/90mcVfBq/unsplash-m-EZ3-Po-FGs-k.jpg",
      email: "KateBoisson@gmail.com",
      role: "Manager",
      contactNumber: "(907)694-7675",
      address: "23475 Glacier View Dr, Eagle River, Alaska 99577, USA",
      id: 12,
    },
    {
      firstName: "Kate",
      lastName: "Boisson 13",
      src: "https://i.postimg.cc/90mcVfBq/unsplash-m-EZ3-Po-FGs-k.jpg",
      email: "KateBoisson@gmail.com",
      role: "Partner",
      contactNumber: "(907)694-7675",
      address: "23475 Glacier View Dr, Eagle River, Alaska 99577, USA",
      id: 13,
    },
    {
      firstName: "Kate",
      lastName: "Boisson 14",
      src: "https://i.postimg.cc/90mcVfBq/unsplash-m-EZ3-Po-FGs-k.jpg",
      email: "KateBoisson@gmail.com",
      role: "Partner",
      contactNumber: "(907)694-7675",
      address: "23475 Glacier View Dr, Eagle River, Alaska 99577, USA",
      id: 14,
    },
    {
      firstName: "Kate",
      lastName: "Boisson 15",
      src: "https://i.postimg.cc/90mcVfBq/unsplash-m-EZ3-Po-FGs-k.jpg",
      email: "KateBoisson@gmail.com",
      role: "Partner",
      contactNumber: "(907)694-7675",
      address: "23475 Glacier View Dr, Eagle River, Alaska 99577, USA",
      id: 15,
    },
    {
      firstName: "Kate",
      lastName: "Boisson 16",
      src: "https://i.postimg.cc/90mcVfBq/unsplash-m-EZ3-Po-FGs-k.jpg",
      email: "KateBoisson@gmail.com",
      role: "Manager",
      contactNumber: "(907)694-7675",
      address: "23475 Glacier View Dr, Eagle River, Alaska 99577, USA",
      id: 16,
    },
    {
      firstName: "Kate",
      lastName: "Boisson 17",
      src: "https://i.postimg.cc/90mcVfBq/unsplash-m-EZ3-Po-FGs-k.jpg",
      email: "KateBoisson@gmail.com",
      role: "Team",
      contactNumber: "(907)694-7675",
      address: "23475 Glacier View Dr, Eagle River, Alaska 99577, USA",
      id: 17,
    },
    {
      firstName: "Kate",
      lastName: "Boisson 18",
      src: "https://i.postimg.cc/90mcVfBq/unsplash-m-EZ3-Po-FGs-k.jpg",
      email: "KateBoisson@gmail.com",
      role: "Partner",
      contactNumber: "(907)694-7675",
      address: "23475 Glacier View Dr, Eagle River, Alaska 99577, USA",
      id: 18,
    },
    {
      firstName: "Kate",
      lastName: "Boisson 19",
      src: "https://i.postimg.cc/90mcVfBq/unsplash-m-EZ3-Po-FGs-k.jpg",
      email: "KateBoisson@gmail.com",
      role: "Manager",
      contactNumber: "(907)694-7675",
      address: "23475 Glacier View Dr, Eagle River, Alaska 99577, USA",
      id: 19,
    },
    {
      firstName: "Kate",
      lastName: "Boisson 20",
      src: "https://i.postimg.cc/90mcVfBq/unsplash-m-EZ3-Po-FGs-k.jpg",
      email: "KateBoisson@gmail.com",
      role: "Partner",
      contactNumber: "(907)694-7675",
      address: "23475 Glacier View Dr, Eagle River, Alaska 99577, USA",
      id: 20,
    },
    {
      firstName: "Kate",
      lastName: "Boisson 21",
      src: "https://i.postimg.cc/90mcVfBq/unsplash-m-EZ3-Po-FGs-k.jpg",
      email: "KateBoisson@gmail.com",
      role: "Partner",
      contactNumber: "(907)694-7675",
      address: "23475 Glacier View Dr, Eagle River, Alaska 99577, USA",
      id: 21,
    },
    {
      firstName: "Kate",
      lastName: "Boisson 22",
      src: "https://i.postimg.cc/90mcVfBq/unsplash-m-EZ3-Po-FGs-k.jpg",
      email: "KateBoisson@gmail.com",
      role: "Partner",
      contactNumber: "(907)694-7675",
      address: "23475 Glacier View Dr, Eagle River, Alaska 99577, USA",
      id: 22,
    },
    {
      firstName: "Kate",
      lastName: "Boisson 23",
      src: "https://i.postimg.cc/90mcVfBq/unsplash-m-EZ3-Po-FGs-k.jpg",
      email: "KateBoisson@gmail.com",
      role: "Manager",
      contactNumber: "(907)694-7675",
      address: "23475 Glacier View Dr, Eagle River, Alaska 99577, USA",
      id: 23,
    },
    {
      firstName: "Kate",
      lastName: "Boisson 24",
      src: "https://i.postimg.cc/90mcVfBq/unsplash-m-EZ3-Po-FGs-k.jpg",
      email: "KateBoisson@gmail.com",
      role: "Team",
      contactNumber: "(907)694-7675",
      address: "23475 Glacier View Dr, Eagle River, Alaska 99577, USA",
      id: 24,
    },
    {
      firstName: "Kate",
      lastName: "Boisson 25",
      src: "https://i.postimg.cc/90mcVfBq/unsplash-m-EZ3-Po-FGs-k.jpg",
      email: "KateBoisson@gmail.com",
      role: "Partner",
      contactNumber: "(907)694-7675",
      address: "23475 Glacier View Dr, Eagle River, Alaska 99577, USA",
      id: 25,
    },
    {
      firstName: "Kate",
      lastName: "Boisson 26",
      src: "https://i.postimg.cc/90mcVfBq/unsplash-m-EZ3-Po-FGs-k.jpg",
      email: "KateBoisson@gmail.com",
      role: "Manager",
      contactNumber: "(907)694-7675",
      address: "23475 Glacier View Dr, Eagle River, Alaska 99577, USA",
      id: 26,
    },
    {
      firstName: "Kate",
      lastName: "Boisson 27",
      src: "https://i.postimg.cc/90mcVfBq/unsplash-m-EZ3-Po-FGs-k.jpg",
      email: "KateBoisson@gmail.com",
      role: "Partner",
      contactNumber: "(907)694-7675",
      address: "23475 Glacier View Dr, Eagle River, Alaska 99577, USA",
      id: 27,
    },
    {
      firstName: "Kate",
      lastName: "Boisson 28",
      src: "https://i.postimg.cc/90mcVfBq/unsplash-m-EZ3-Po-FGs-k.jpg",
      email: "KateBoisson@gmail.com",
      role: "Partner",
      contactNumber: "(907)694-7675",
      address: "23475 Glacier View Dr, Eagle River, Alaska 99577, USA",
      id: 28,
    },
    {
      firstName: "Kate",
      lastName: "Boisson 29",
      src: "https://i.postimg.cc/90mcVfBq/unsplash-m-EZ3-Po-FGs-k.jpg",
      email: "KateBoisson@gmail.com",
      role: "Partner",
      contactNumber: "(907)694-7675",
      address: "23475 Glacier View Dr, Eagle River, Alaska 99577, USA",
      id: 29,
    },
    {
      firstName: "Kate",
      lastName: "Boisson 30",
      src: "https://i.postimg.cc/90mcVfBq/unsplash-m-EZ3-Po-FGs-k.jpg",
      email: "KateBoisson@gmail.com",
      role: "Manager",
      contactNumber: "(907)694-7675",
      address: "23475 Glacier View Dr, Eagle River, Alaska 99577, USA",
      id: 30,
    },
    {
      firstName: "Kate",
      lastName: "Boisson 31",
      src: "https://i.postimg.cc/90mcVfBq/unsplash-m-EZ3-Po-FGs-k.jpg",
      email: "KateBoisson@gmail.com",
      role: "Team",
      contactNumber: "(907)694-7675",
      address: "23475 Glacier View Dr, Eagle River, Alaska 99577, USA",
      id: 31,
    },
    {
      firstName: "Kate",
      lastName: "Boisson 32",
      src: "https://i.postimg.cc/90mcVfBq/unsplash-m-EZ3-Po-FGs-k.jpg",
      email: "KateBoisson@gmail.com",
      role: "Partner",
      contactNumber: "(907)694-7675",
      address: "23475 Glacier View Dr, Eagle River, Alaska 99577, USA",
      id: 32,
    },
    {
      firstName: "Kate",
      lastName: "Boisson 33",
      src: "https://i.postimg.cc/90mcVfBq/unsplash-m-EZ3-Po-FGs-k.jpg",
      email: "KateBoisson@gmail.com",
      role: "Manager",
      contactNumber: "(907)694-7675",
      address: "23475 Glacier View Dr, Eagle River, Alaska 99577, USA",
      id: 33,
    },
    {
      firstName: "Kate",
      lastName: "Boisson 34",
      src: "https://i.postimg.cc/90mcVfBq/unsplash-m-EZ3-Po-FGs-k.jpg",
      email: "KateBoisson@gmail.com",
      role: "Partner",
      contactNumber: "(907)694-7675",
      address: "23475 Glacier View Dr, Eagle River, Alaska 99577, USA",
      id: 34,
    },
    {
      firstName: "Kate",
      lastName: "Boisson 35",
      src: "https://i.postimg.cc/90mcVfBq/unsplash-m-EZ3-Po-FGs-k.jpg",
      email: "KateBoisson@gmail.com",
      role: "Partner",
      contactNumber: "(907)694-7675",
      address: "23475 Glacier View Dr, Eagle River, Alaska 99577, USA",
      id: 35,
    },
    {
      firstName: "Kate",
      lastName: "Boisson 36",
      src: "https://i.postimg.cc/90mcVfBq/unsplash-m-EZ3-Po-FGs-k.jpg",
      email: "KateBoisson@gmail.com",
      role: "Partner",
      contactNumber: "(907)694-7675",
      address: "23475 Glacier View Dr, Eagle River, Alaska 99577, USA",
      id: 36,
    },
    {
      firstName: "Kate",
      lastName: "Boisson 37",
      src: "https://i.postimg.cc/90mcVfBq/unsplash-m-EZ3-Po-FGs-k.jpg",
      email: "KateBoisson@gmail.com",
      role: "Manager",
      contactNumber: "(907)694-7675",
      address: "23475 Glacier View Dr, Eagle River, Alaska 99577, USA",
      id: 37,
    },
    {
      firstName: "Kate",
      lastName: "Boisson 38",
      src: "https://i.postimg.cc/90mcVfBq/unsplash-m-EZ3-Po-FGs-k.jpg",
      email: "KateBoisson@gmail.com",
      role: "Team",
      contactNumber: "(907)694-7675",
      address: "23475 Glacier View Dr, Eagle River, Alaska 99577, USA",
      id: 38,
    },
    {
      firstName: "Kate",
      lastName: "Boisson 39",
      src: "https://i.postimg.cc/90mcVfBq/unsplash-m-EZ3-Po-FGs-k.jpg",
      email: "KateBoisson@gmail.com",
      role: "Partner",
      contactNumber: "(907)694-7675",
      address: "23475 Glacier View Dr, Eagle River, Alaska 99577, USA",
      id: 39,
    },
    {
      firstName: "Kate",
      lastName: "Boisson 40",
      src: "https://i.postimg.cc/90mcVfBq/unsplash-m-EZ3-Po-FGs-k.jpg",
      email: "KateBoisson@gmail.com",
      role: "Manager",
      contactNumber: "(907)694-7675",
      address: "23475 Glacier View Dr, Eagle River, Alaska 99577, USA",
      id: 40,
    },
    {
      firstName: "Kate",
      lastName: "Boisson 41",
      src: "https://i.postimg.cc/90mcVfBq/unsplash-m-EZ3-Po-FGs-k.jpg",
      email: "KateBoisson@gmail.com",
      role: "Partner",
      contactNumber: "(907)694-7675",
      address: "23475 Glacier View Dr, Eagle River, Alaska 99577, USA",
      id: 41,
    },
    {
      firstName: "Kate",
      lastName: "Boisson 42",
      src: "https://i.postimg.cc/90mcVfBq/unsplash-m-EZ3-Po-FGs-k.jpg",
      email: "KateBoisson@gmail.com",
      role: "Partner",
      contactNumber: "(907)694-7675",
      address: "23475 Glacier View Dr, Eagle River, Alaska 99577, USA",
      id: 42,
    },
  ],
};

export default data;
